// src/lib/stores.js — All 114 Kreamz outlets (from AFE Dashboard April 2026)
export const STORES = [
  { id: "KRZ-001", name: "A To Z Solution", afe: "Abir Naskar" },
  { id: "KRZ-002", name: "Aabhis Innovation", afe: "Abir Naskar" },
  { id: "KRZ-003", name: "Dainty Delight", afe: "Abir Naskar" },
  { id: "KRZ-004", name: "Dainty Delights", afe: "Abir Naskar" },
  { id: "KRZ-005", name: "Das Confectionery", afe: "Abir Naskar" },
  { id: "KRZ-006", name: "Debarati Cakes And More", afe: "Abir Naskar" },
  { id: "KRZ-007", name: "Delicious Confectionery", afe: "Abir Naskar" },
  { id: "KRZ-008", name: "Dhir Enterprise", afe: "Abir Naskar" },
  { id: "KRZ-009", name: "Dipankar Snacks And Cakes", afe: "Abir Naskar" },
  { id: "KRZ-010", name: "Durga Enterprise", afe: "Abir Naskar" },
  { id: "KRZ-011", name: "Nandi Confansary", afe: "Abir Naskar" },
  { id: "KRZ-012", name: "Naskar Yummy And Tasty", afe: "Abir Naskar" },
  { id: "KRZ-013", name: "Nayeem Confectionery", afe: "Abir Naskar" },
  { id: "KRZ-014", name: "Reyansh Confectionery", afe: "Abir Naskar" },
  { id: "KRZ-015", name: "S. D. Enterprise", afe: "Abir Naskar" },
  { id: "KRZ-016", name: "Sn Enterprise", afe: "Abir Naskar" },
  { id: "KRZ-017", name: "Ajit Store", afe: "Arijit Sen" },
  { id: "KRZ-018", name: "Bakers Bliss", afe: "Arijit Sen" },
  { id: "KRZ-019", name: "Cakes And Snacks Club", afe: "Arijit Sen" },
  { id: "KRZ-020", name: "Manmohan Cake Shop", afe: "Arijit Sen" },
  { id: "KRZ-021", name: "Maple Leaf", afe: "Arijit Sen" },
  { id: "KRZ-022", name: "Rajdeep Bakery And Cake", afe: "Arijit Sen" },
  { id: "KRZ-023", name: "Sri Hari Foods", afe: "Arijit Sen" },
  { id: "KRZ-024", name: "Sudha Confectionery", afe: "Arijit Sen" },
  { id: "KRZ-025", name: "Urmila Enterprise", afe: "Arijit Sen" },
  { id: "KRZ-026", name: "Arvind Stores", afe: "Indranil Dey" },
  { id: "KRZ-027", name: "Bhuban Confectionary", afe: "Indranil Dey" },
  { id: "KRZ-028", name: "Fresh Flavours", afe: "Indranil Dey" },
  { id: "KRZ-029", name: "Ganesh Indulgence", afe: "Indranil Dey" },
  { id: "KRZ-030", name: "Mona Snacks", afe: "Indranil Dey" },
  { id: "KRZ-031", name: "Nailah Enterprise", afe: "Indranil Dey" },
  { id: "KRZ-032", name: "Paul Confectionery", afe: "Indranil Dey" },
  { id: "KRZ-033", name: "Renew Retail 2", afe: "Indranil Dey" },
  { id: "KRZ-034", name: "Sri Krishna Cake Canvas", afe: "Indranil Dey" },
  { id: "KRZ-035", name: "Suroop Ventures", afe: "Indranil Dey" },
  { id: "KRZ-036", name: "Adiraj Ice And Cakes", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-037", name: "Aradhya Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-038", name: "Baidik", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-039", name: "Bhagyashri", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-040", name: "Bose Enterprise", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-041", name: "Cakeology", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-042", name: "Das Enterprises", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-043", name: "Debran Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-044", name: "Dina Nath Enterprise", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-045", name: "Durga Ram Stores", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-046", name: "Kinza Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-047", name: "Kreamz", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-048", name: "Maa Tara Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-049", name: "Maya Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-050", name: "Misti Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-051", name: "Namita Store", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-052", name: "Papiya Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-053", name: "Paradise Book Company", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-054", name: "Purnima Confectionery", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-055", name: "Saanviz", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-056", name: "Somas Stop", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-057", name: "Taniskaas Chocos Charm", afe: "Partha Sarathi Bhattacharjee" },
  { id: "KRZ-058", name: "Anjali Cake Shop", afe: "Pratik Neogi" },
  { id: "KRZ-059", name: "Barman Confectionery", afe: "Pratik Neogi" },
  { id: "KRZ-060", name: "Bonny\'S Bakery", afe: "Pratik Neogi" },
  { id: "KRZ-061", name: "Cristal Rockks Cakes And Bakery Shop", afe: "Pratik Neogi" },
  { id: "KRZ-062", name: "Dolly Confectionery", afe: "Pratik Neogi" },
  { id: "KRZ-063", name: "Rayyan Confectionery", afe: "Pratik Neogi" },
  { id: "KRZ-064", name: "Sarthak Enterprise", afe: "Pratik Neogi" },
  { id: "KRZ-065", name: "Srv Enterprise", afe: "Pratik Neogi" },
  { id: "KRZ-066", name: "A P Hospitality", afe: "Ratan Roy" },
  { id: "KRZ-067", name: "Diya Confectionery", afe: "Ratan Roy" },
  { id: "KRZ-068", name: "Dream Confectionery", afe: "Ratan Roy" },
  { id: "KRZ-069", name: "Paul Enterprise", afe: "Ratan Roy" },
  { id: "KRZ-070", name: "S S Enterprise", afe: "Ratan Roy" },
  { id: "KRZ-071", name: "S.S. Enterprise", afe: "Ratan Roy" },
  { id: "KRZ-072", name: "Sagar Enterprises", afe: "Ratan Roy" },
  { id: "KRZ-073", name: "Sankari Food Mart", afe: "Ratan Roy" },
  { id: "KRZ-074", name: "Souvik Cake Centre", afe: "Ratan Roy" },
  { id: "KRZ-075", name: "Suman Dutta Confectionery", afe: "Ratan Roy" },
  { id: "KRZ-076", name: "Sunrise", afe: "Ratan Roy" },
  { id: "KRZ-077", name: "Urban Confactionery", afe: "Ratan Roy" },
  { id: "KRZ-078", name: "Utsav Confectionery", afe: "Ratan Roy" },
  { id: "KRZ-079", name: "Aaron Confectionery", afe: "Saikat Roy" },
  { id: "KRZ-080", name: "Arya Sweets Snacks And Fast Food Centre", afe: "Saikat Roy" },
  { id: "KRZ-081", name: "Asha Confectionery And Bevarage", afe: "Saikat Roy" },
  { id: "KRZ-082", name: "Chandana Confectionery", afe: "Saikat Roy" },
  { id: "KRZ-083", name: "Cookies Corner", afe: "Saikat Roy" },
  { id: "KRZ-084", name: "Das Fast Food", afe: "Saikat Roy" },
  { id: "KRZ-085", name: "Dey Confectionery", afe: "Saikat Roy" },
  { id: "KRZ-086", name: "Elite Bakers", afe: "Saikat Roy" },
  { id: "KRZ-087", name: "Kakes", afe: "Saikat Roy" },
  { id: "KRZ-088", name: "Maa Annapurna Confectionery", afe: "Saikat Roy" },
  { id: "KRZ-089", name: "Roys Confectionery", afe: "Saikat Roy" },
  { id: "KRZ-090", name: "Sns Enterprise", afe: "Saikat Roy" },
  { id: "KRZ-091", name: "Supriti 365", afe: "Saikat Roy" },
  { id: "KRZ-092", name: "The Aadda Zone", afe: "Saikat Roy" },
  { id: "KRZ-093", name: "Vinayak Traders", afe: "Saikat Roy" },
  { id: "KRZ-094", name: "Adimou Delicious Enterprise", afe: "Soumen Roy" },
  { id: "KRZ-095", name: "Aneek Enterprise", afe: "Soumen Roy" },
  { id: "KRZ-096", name: "Atithi", afe: "Soumen Roy" },
  { id: "KRZ-097", name: "Awtar Enterprise", afe: "Soumen Roy" },
  { id: "KRZ-098", name: "Ballygunje Cake Shop", afe: "Soumen Roy" },
  { id: "KRZ-099", name: "Cinzano", afe: "Soumen Roy" },
  { id: "KRZ-100", name: "Delectable Confectionery", afe: "Soumen Roy" },
  { id: "KRZ-101", name: "Dharon", afe: "Soumen Roy" },
  { id: "KRZ-102", name: "Divine Treatz", afe: "Soumen Roy" },
  { id: "KRZ-103", name: "Kidi Max Traders", afe: "Soumen Roy" },
  { id: "KRZ-104", name: "Mahamaya", afe: "Soumen Roy" },
  { id: "KRZ-105", name: "R Sarkar Confectionery", afe: "Soumen Roy" },
  { id: "KRZ-106", name: "Rm Enterprise", afe: "Soumen Roy" },
  { id: "KRZ-107", name: "Rs Enterprises", afe: "Soumen Roy" },
  { id: "KRZ-108", name: "Shivam Confectionery", afe: "Soumen Roy" },
  { id: "KRZ-109", name: "Tasty Treats", afe: "Soumen Roy" },
  { id: "KRZ-110", name: "A S Sales Corporation", afe: "Unassigned" },
  { id: "KRZ-111", name: "Mira Confectionery", afe: "Unassigned" },
  { id: "KRZ-112", name: "Purnima Cakes", afe: "Unassigned" },
  { id: "KRZ-113", name: "Renew Retail", afe: "Unassigned" },
  { id: "KRZ-114", name: "Tritiya Bake House", afe: "Unassigned" },
];

export const STORE_NAMES = STORES.map(s => s.name);

export function getStoreById(id) {
  return STORES.find(s => s.id === id);
}

export function getStoreByName(name) {
  return STORES.find(s => s.name === name);
}
